# 应用名称
spring:
  application:
    name: sms-message
  datasource:
    #配置当前使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #配置MySQL的驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #数据库连接用户名
    username: root
    #数据库连接密码
    password: 258036
    #进行数据库连接池的配置
    dbcp2:
      #初始化提供的连接数
      initial-size: 5
      #数据库连接池的最小维持连接数
      min-idle: 5
      #最大的连接数
      max-total: 5
      #等待连接获取的最大超时时间
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    hikari:
      leak-detection-threshold:
  security:
    user:
      name: root
      password: root
  sleuth:
    sampler:
      rate: 1
  zipkin:
    base-url: http://127.0.0.1:9411/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    virtual-host-name: sms-message
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

#mybatis配置
mybatis:
  #mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  #所有的mapper映射文件
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
---
server:
  port: 8082
spring:
  profiles: 8082

---
spring:
  profiles: 8081
server:
  port: 8081



