
spring:
  application:
    name: Eureka-Server-01
eureka:
  client:
    eureka-server-port: 7001
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
server:
  port: 7001

